---
# handlers file for roles/optimize
- name: systemctl daemon-reexec
  shell: systemctl daemon-reexec

- name: restart sshd
  service:
    name: sshd
    state: restarted

- name: source /etc/profile
  shell: source /etc/profile

- name: source rc.local
  shell: source /etc/rc.d/rc.local

- name: restart chronyd
  service:
    name: chronyd
    state: restarted
    enabled: yes

- name: sysctl -p
  shell: sysctl -p

- name: reboot
  reboot:

