- name: Get master status
  mysql_replication:
    login_user: root
    login_password: "{{mysql_password}}"
    mode: getmaster
  register: master_info

- name: Add sync user remote access
  mysql_user:
    login_user: root
    login_password: "{{mysql_password}}"
    host: '%'
    name: "{{master_user}}"
    password: "{{master_password}}"
    priv: '*.*:ALL,GRANT'
    state: present
  when: master_info.Is_Master

- name: Get master binlog file name and binlog position
  mysql_replication:
    login_user: root
    login_password: "{{mysql_password}}"
    mode: getmaster
  delegate_to: "{{groups.mysql_master[0]}}"
  register: master_info

#- name: Stop mysql slave thread
#  mysql_replication:
#    login_user: root
#    login_password: "{{mysql_password}}"
#    mode: stopslave

- name: sync master db 
  mysql_replication:
    login_user: root
    login_password: "{{mysql_password}}"
    mode: changemaster
    master_user: "{{master_user}}"
    master_password: "{{master_password}}"
    master_host: "{{groups.mysql_master[0]}}"
    master_log_file: "{{master_info.File}}"
    master_log_pos: "{{master_info.Position}}"
  when: ansible_all_ipv4_addresses == groups.mysql_slave

- name: start mysql slave thread
  mysql_replication:
    login_user: root
    login_password: "{{mysql_password}}"
    mode: startslave
  when: ansible_all_ipv4_addresses == groups.mysql_slave
